### ISSUE TITLE
Ficheros con los datos de los vehículos (Hito - 20 de abril)

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-twq103-alquicar#2]
Hola:

Os comento lo que veo de vuestra primera entrega y os propongo añadirle más funcionalidad.

El menú está muy bien.

El hito que os propongo para el 20 de abril es que creéis un fichero de texto (.txt) con todos los vehículos y se muestre por pantalla cuando se pulse la opción correspondiente. Os aconsejo que almacenéis los datos en un vector de estructuras.

Además de esto, os animo a que sigáis programando más funcionalidades.

Un saludo y buenas vacaciones.

**Comment by BarbaraCulebras** [comment]
Todo subido.
