### ISSUE TITLE
Entrega final: Código y memoria del trabajo (Wiki)

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-twq103-alquicar#4]
Subir el fichero final .c al repositorio (subir el archivo con el mismo nombre).

Hacer una Wiki para describir el trabajo. El qué incluir y cómo hacerlo está explicado aquí:
https://github.com/aigora/punto_inicio/wiki/6.-C%C3%B3mo-presentar-el-trabajo

Acordaos de cerrar las issues para que me llegue una notificación.

**Comment by LaLola1** [comment]
Hecho

**Comment by BarbaraCulebras** [comment]
Cerrado
